// /godcode primitives — public surface.
export { gateRunner, runCmd, parseTap, parseTapDetailed, tapComplete, parseTrx, parseTrxDetailed, trxComplete, RESULTS_DIR_TOKEN, DEFAULT_PROTECTED_DOTNET, DEFAULT_PROTECTED_VITEST } from './gate-runner.mjs';
export { dispersion, hammingDistance, signatureFromResults } from './dispersion.mjs';
export { fanoutSelect } from './fanout-select.mjs';
export { generateMutationProbes, runMutationProbes, validateMutationRows } from './mutation-probes.mjs';
export { authorLoop } from './author-loop.mjs';
export { runWaves } from './runner.mjs';
export { stopDecision } from './stopRule.mjs';
export { triage, classifyRegime, wilsonInterval } from './triage.mjs';
export { select } from './harness.mjs';
export { runGate } from './gate.mjs';
export { RunDossier, renderDossier } from './dossier.mjs';
export { validateCertificate, certifyVerifier } from './certify.mjs';
export { constructProseVerifier, assembleForCertify } from './construct-prose-verifier.mjs';
export { emitProseVerifier, validateClaims, evaluateClaim, evaluateClaims, proseExample } from './prose-verifier.mjs';
export { bleedLint } from './bleed-lint.mjs';
export { rankByProxies, advisoryRank, buildSlate } from './slate.mjs';
export { orchestrateObjective, judgeFnFromVerdicts, classifyGate, authorIsDecorrelated, resolveAnswerAuthor, pickBestFailing, NO_VERDICT } from './orchestrate.mjs';
export { orchestrateProse, defaultProseProxies } from './orchestrate-prose.mjs';
export { emitHtmlVerifier, evaluateChecks, decideCheck, planFor, probeJs, validateHtmlChecks, renderSnapshot, runHtmlVerifier, htmlExample } from './html-verifier.mjs';
export { constructHtmlVerifier, assembleHtmlForCertify } from './construct-html-verifier.mjs';
export { orchestrateHtml, defaultHtmlProxies } from './orchestrate-html.mjs';
